<?php

namespace Database\Seeders;

use App\Models\Escuela;
use App\Models\Programa;
use App\Models\Usuario;
use Illuminate\Database\Seeder;

class ProgramaSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = Usuario::where('usuario', 'admin')->value('id');

        if (! $adminId) {
            $this->call(UsuarioSeeder::class);
            $adminId = Usuario::where('usuario', 'admin')->value('id');
        }

        $programas = [
            [
                                    'codigo_pro' => '30225',
                                    'nombre' => 'Administración Ambiental Y De Los Recursos Naturales',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '101',
                                    'nombre' => 'Administración De Empresas',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '126',
                                    'nombre' => 'Administración Empresas (Innovación Curricular)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '151',
                                    'nombre' => 'Administracion En Salud',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '15297',
                                    'nombre' => 'Administración En Salud',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30240',
                                    'nombre' => 'Agronomía',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '352',
                                    'nombre' => 'Agronomia',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40335',
                                    'nombre' => 'Artes Visuales',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '408',
                                    'nombre' => 'Artes Visuales',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '252',
                                    'nombre' => 'Ciencia Politica',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10352',
                                    'nombre' => 'Coach - Desarrollo Organizacional, Económico E Industrial',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '441',
                                    'nombre' => 'Comunicación Social',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40248',
                                    'nombre' => 'Comunicación Social Res (19845)',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10361',
                                    'nombre' => 'Contaduria Publica',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '106',
                                    'nombre' => 'Contaduría Pública',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100178',
                                    'nombre' => 'Convenio Especifico Asociación Nacional De Empresarios De Colombia Andi 2025 - Peraca 1894',
                                    'escuela_sigla' => 'SINEC',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100174',
                                    'nombre' => 'Convenio Fiduciaria De Comercio Exterior S',
                                    'escuela_sigla' => 'SINEC',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100177',
                                    'nombre' => 'Convenio Fiduciaria De Comercio Exterior S',
                                    'escuela_sigla' => 'SINEC',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100179',
                                    'nombre' => 'Convenio Fiduciaria De Comercio Exterior S',
                                    'escuela_sigla' => 'SINEC',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100176',
                                    'nombre' => 'Convenio Inst De Invest De Recursos Biologicos Alexander Von Humboldt 2025',
                                    'escuela_sigla' => 'SINEC',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100066',
                                    'nombre' => 'Convenio Superintendencia Del Subsidio Familiar - Unad 9 2021',
                                    'escuela_sigla' => 'SINEC',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '251',
                                    'nombre' => 'Derecho',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '218',
                                    'nombre' => 'Diseño Industrial',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10276',
                                    'nombre' => 'Economía',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '105',
                                    'nombre' => 'Economia',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '905',
                                    'nombre' => 'Español Para Todos',
                                    'escuela_sigla' => 'INVIL',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10257',
                                    'nombre' => 'Especialización En Alta Gerencia Y Desarrollo Organizacional',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30239',
                                    'nombre' => 'Especialización En Biotecnología Agroambiental',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20300',
                                    'nombre' => 'Especialización En Ciencia De Datos Y Analítica',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '25311',
                                    'nombre' => 'Especialización En Derecho Administrativo',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10308',
                                    'nombre' => 'Especialización En Dirección Y Desarrollo Del Talento Humano',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '516',
                                    'nombre' => 'Especialización En Educación Superior A Distancia (Resolución 02030)',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50329',
                                    'nombre' => 'Especialización En Educación Superior Y Transformación Digital',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '502',
                                    'nombre' => 'Especializacion En Educacion, Cultura Y Politica',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50348',
                                    'nombre' => 'Especialización En Educación, Cultura Y Política',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10231',
                                    'nombre' => 'Especialización En Finanzas Corporativas',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '228',
                                    'nombre' => 'Especializacion En Gerencia De Procesos Logisticos En Redes De Valor',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10251',
                                    'nombre' => 'Especialización En Gerencia Estratégica De Mercadeo (Resolucion 009939)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '122',
                                    'nombre' => 'Especializacion En Gerencia Estrategica De Mercadeo',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '15310',
                                    'nombre' => 'Especialización En Gerencia Y Auditoría De La Calidad En Salud',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10243',
                                    'nombre' => 'Especialización En Gestión De Proyectos (Resolucion 3490)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '104',
                                    'nombre' => 'Especialización En Gestión De Proyectos (Resolución 987)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '25265',
                                    'nombre' => 'Especializacion En Gestion Publica (Resolucion 010388)',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '123',
                                    'nombre' => 'Especializacion En Gestion Publica (Resolucion 07817)',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10278',
                                    'nombre' => 'Especialización En Inteligencia E Innovación Organizacional',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50340',
                                    'nombre' => 'Especialización En Neuropedagogía Y Aprendizaje Autónomo',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30244',
                                    'nombre' => 'Especializacion En Nutricion Y Alimentacion Animal Sostenible (Resolucion 4737)',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '521',
                                    'nombre' => 'Especialización En Pedagogía Para El Desarrollo Del Aprendizaje Autónomo',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40317',
                                    'nombre' => 'Especializacion En Psicología Jurídica',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '219',
                                    'nombre' => 'Especializacion En Redes De Nueva Generacion',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20345',
                                    'nombre' => 'Especialización En Redes De Telecomunicaciones',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30242',
                                    'nombre' => 'Especialización En Responsabilidad Social Y Ambiental',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40292',
                                    'nombre' => 'Especialización En Salud Mental Comunitaria',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20237',
                                    'nombre' => 'Especialización En Seguridad Informática (Resolución 11681)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '407',
                                    'nombre' => 'Filosofia (Resolucion 10583)',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40272',
                                    'nombre' => 'Filosofía',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10299',
                                    'nombre' => 'Finanzas Y Comercio Internacional',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '452',
                                    'nombre' => 'Formacion Pedagogica Para Docentes',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '903',
                                    'nombre' => 'Francés',
                                    'escuela_sigla' => 'INVIL',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '453',
                                    'nombre' => 'Gestion Deportiva',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40316',
                                    'nombre' => 'Historia',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30227',
                                    'nombre' => 'Ingenieria Agroforestal',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '353',
                                    'nombre' => 'Ingenieria Agroforestal',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30293',
                                    'nombre' => 'Ingeniería Ambiental',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '358',
                                    'nombre' => 'Ingenieria Ambiental',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20313',
                                    'nombre' => 'Ingenieria De Alimentos (Resolución 014448 2023)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '216',
                                    'nombre' => 'Ingenieria De Alimentos (Resolucion 0575)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '211',
                                    'nombre' => 'Ingenieria De Alimentos (Resolución 9429)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20233',
                                    'nombre' => 'Ingeniería De Sistemas (Resolución 011685)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '201',
                                    'nombre' => 'Ingenieria De Sistemas',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '208',
                                    'nombre' => 'Ingenieria De Telecomunicaciones (Resolución 14518)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20306',
                                    'nombre' => 'Ingeniería De Telecomunicaciones (Resolución 15494)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20303',
                                    'nombre' => 'Ingeniería Electrónica (Resolución 10431)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '203',
                                    'nombre' => 'Ingeniería Electrónica (Resolución 13155)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '212',
                                    'nombre' => 'Ingenieria Industrial (Resolución 05867)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20341',
                                    'nombre' => 'Ingenieria Industrial',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '245',
                                    'nombre' => 'Ingeniería Multimedia',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '902',
                                    'nombre' => 'Ingles Para Niños',
                                    'escuela_sigla' => 'INVIL',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50270',
                                    'nombre' => 'Licenciatura En Educación Infantil',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50236',
                                    'nombre' => 'Licenciatura En Etnoeducación - Resolución N 011684',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '446',
                                    'nombre' => 'Licenciatura En Etnoeducacion',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '520',
                                    'nombre' => 'Licenciatura En Filosofia (Resolución 12423)',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '510',
                                    'nombre' => 'Licenciatura En Ingles Como Lengua Extranjera',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50343',
                                    'nombre' => 'Licenciatura En Lenguas Extranjeras Con Enfasis En Ingles',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '518',
                                    'nombre' => 'Licenciatura En Lenguas Extranjeras Con Énfasis En Inglés',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '522',
                                    'nombre' => 'Licenciatura En Matematicas (Resolución 1049 De 2019)',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '511',
                                    'nombre' => 'Licenciatura En Matematicas',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '514',
                                    'nombre' => 'Licenciatura En Pedagogia Infantil',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20250',
                                    'nombre' => 'Maestría  En Diseño De Experiencia De Usuario',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '125',
                                    'nombre' => 'Maestria En Administracion De Organizaciones (Resolución 20520)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10344',
                                    'nombre' => 'Maestria En Administracion De Organizaciones',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '107',
                                    'nombre' => 'Maestria En Administracion De Organizaciones',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30211',
                                    'nombre' => 'Maestria En Agronegocios',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '15322',
                                    'nombre' => 'Maestría En Bioética',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20234',
                                    'nombre' => 'Maestría En Biotecnología Alimentaria',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20302',
                                    'nombre' => 'Maestría En Ciberseguridad',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20323',
                                    'nombre' => 'Maestría En Ciencia De Datos Y Analítica (Resolución 005028 2024)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40273',
                                    'nombre' => 'Maestría En Comunicación',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '406',
                                    'nombre' => 'Maestria En Comunicacion',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '25326',
                                    'nombre' => 'Maestria En Derecho',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40274',
                                    'nombre' => 'Maestría En Desarrollo Alternativo, Sostenible Y Solidario',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '405',
                                    'nombre' => 'Maestria En Desarrollo Alternativo, Sostenible Y Solidario',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30277',
                                    'nombre' => 'Maestría En Desarrollo Rural (Modalidad Investigación)',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30269',
                                    'nombre' => 'Maestría En Desarrollo Rural (Modalidad Profundización)',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50230',
                                    'nombre' => 'Maestría En Educación',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50229',
                                    'nombre' => 'Maestría En Educación Intercultural',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50280',
                                    'nombre' => 'Maestría En Educación Matemática',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40318',
                                    'nombre' => 'Maestria En Filosofía De La Tecnología',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30281',
                                    'nombre' => 'Maestría En Geoinformación Del Territorio',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20208',
                                    'nombre' => 'Maestria En Gerencia De Proyectos',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10309',
                                    'nombre' => 'Maestría En Gestión Analítica Y Estratégica De Personas',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20338',
                                    'nombre' => 'Maestria En Gestion De Tecnologia De Informacion',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '214',
                                    'nombre' => 'Maestria En Gestion De Tecnologia De Informacion',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10210',
                                    'nombre' => 'Maestria En Gestion Financiera',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '25254',
                                    'nombre' => 'Maestria En Gobierno, Politicas Publicas Y Desarrollo Territorial',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20301',
                                    'nombre' => 'Maestría En Internet De Las Cosas',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20294',
                                    'nombre' => 'Maestría En Logística Y Redes De Valor',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10252',
                                    'nombre' => 'Maestría En Marketing',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '50228',
                                    'nombre' => 'Maestría En Mediación Pedagógica En El Aprendizaje Del Inglés',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '25275',
                                    'nombre' => 'Maestría En Política, Derecho Y Gestión Ambiental',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10298',
                                    'nombre' => 'Maestría En Prospectiva E Innovación Sostenible',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40291',
                                    'nombre' => 'Maestría En Psicología Comunitaria',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '409',
                                    'nombre' => 'Maestria En Psicologia Comunitaria',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '15305',
                                    'nombre' => 'Maestría En Telesalud',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10296',
                                    'nombre' => 'Marketing Y Negocios Digitales',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100032',
                                    'nombre' => 'Movilidad 1',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100035',
                                    'nombre' => 'Movilidad 2',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100034',
                                    'nombre' => 'Movilidad 3',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100037',
                                    'nombre' => 'Movilidad 4',
                                    'escuela_sigla' => 'ECEDU',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100036',
                                    'nombre' => 'Movilidad 5Lud',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100038',
                                    'nombre' => 'Movilidad 6',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100033',
                                    'nombre' => 'Movilidad 7',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40334',
                                    'nombre' => 'Música',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '410',
                                    'nombre' => 'Musica',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '127',
                                    'nombre' => 'Negocios Internacionales',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '904',
                                    'nombre' => 'Portugués',
                                    'escuela_sigla' => 'INVIL',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '15304',
                                    'nombre' => 'Profesional En Seguridad Y Salud En El Trabajo',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '440',
                                    'nombre' => 'Programa De Alfabetización, Educación Básica Y Media',
                                    'escuela_sigla' => 'SINEP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '100173',
                                    'nombre' => 'Programas De Educación Continuada 2025 08-01 - Peraca 2161',
                                    'escuela_sigla' => 'SINEC',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '403',
                                    'nombre' => 'Psicologia (Resolución 3443)',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40253',
                                    'nombre' => 'Psicologia',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '40271',
                                    'nombre' => 'Sociología',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '404',
                                    'nombre' => 'Sociologia',
                                    'escuela_sigla' => 'ECSAH',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '243',
                                    'nombre' => 'Tecnologia En Automatizacion Electronica',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20268',
                                    'nombre' => 'Tecnología En Automatización Electrónica Industrial (Resolución 020924)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '217',
                                    'nombre' => 'Tecnología En Calidad Alimentaria',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '204',
                                    'nombre' => 'Tecnologia En Desarollo De Software',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20290',
                                    'nombre' => 'Tecnología En Desarrollo De Software (Resolución 025437)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '116',
                                    'nombre' => 'Tecnologia En Gestion Agropecuaria (Resolucion 12019)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10247',
                                    'nombre' => 'Tecnología En Gestión Comercial Y De Negocios (Resolución 014429 De 2023)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '110',
                                    'nombre' => 'Tecnologia En Gestion Comercial Y De Negocios (Resolución 6544)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10255',
                                    'nombre' => 'Tecnología En Gestión De Agronegocios',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '120',
                                    'nombre' => 'Tecnología En Gestión De Empresas Asociativas Y Organizaciones Comunitarias (Resolución 12020)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10266',
                                    'nombre' => 'Tecnologia En Gestión De Empresas Y Organizaciones Solidarias (Resolución 5101)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10245',
                                    'nombre' => 'Tecnología En Gestión De Obras Civiles Y Construcciones (Resolución 006877 2023)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '103',
                                    'nombre' => 'Tecnologia En Gestion De Obras Civiles Y Construcciones (Resolucion 95)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20238',
                                    'nombre' => 'Tecnología En Gestión De Redes Inalámbricas',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '102',
                                    'nombre' => 'Tecnología En Gestión De Transportes (Resolución 99)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '10246',
                                    'nombre' => 'Tecnología En Gestión De Transportes',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '121',
                                    'nombre' => 'Tecnologia En Gestion Industrial (Resolucion 16616)',
                                    'escuela_sigla' => 'ECACEN',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '253',
                                    'nombre' => 'Tecnologia En Gestion Juridica De La Informacion',
                                    'escuela_sigla' => 'ECJP',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20249',
                                    'nombre' => 'Tecnología En Logística Industrial',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '242',
                                    'nombre' => 'Tecnologia En Logistica Industrial',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30254',
                                    'nombre' => 'Tecnología En Manejo Y Comercialización Agroforestal',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30241',
                                    'nombre' => 'Tecnología En Producción Agrícola',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '350',
                                    'nombre' => 'Tecnologia En Produccion Agricola',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30267',
                                    'nombre' => 'Tecnologia En Produccion Animal (Resolución 005379 De 2023)',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '331',
                                    'nombre' => 'Tecnologia En Produccion Animal (Resolucion 17682)',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '20333',
                                    'nombre' => 'Tecnología En Producción De Audio (Resolución 23926)',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '213',
                                    'nombre' => 'Tecnología En Producción De Audio',
                                    'escuela_sigla' => 'ECBTI',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '154',
                                    'nombre' => 'Tecnologia En Radiologia E Imagenes Diagnosticas',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '152',
                                    'nombre' => 'Tecnologia En Regencia De Farmacia (Resolucion 08200)',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '15321',
                                    'nombre' => 'Tecnologia En Regencia De Farmacia (Resolución 1309 De 2023)',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '221',
                                    'nombre' => 'Tecnologia En Regencia De Farmacia',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '301',
                                    'nombre' => 'Tecnologia En Saneamiento Ambiental (Resolucion 13396)',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '153',
                                    'nombre' => 'Tecnologia En Seguridad Y Salud En El Trabajo',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '15324',
                                    'nombre' => 'Tecnología En Seguridad Y Salud En El Trabajo',
                                    'escuela_sigla' => 'ECISA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '304',
                                    'nombre' => 'Tecnologia En Sistemas Agroforestales',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '907',
                                    'nombre' => 'Unad Chino-Mandarin',
                                    'escuela_sigla' => 'INVIL',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '901',
                                    'nombre' => 'Unad English',
                                    'escuela_sigla' => 'INVIL',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '906',
                                    'nombre' => 'Unad Italiano',
                                    'escuela_sigla' => 'INVIL',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '30226',
                                    'nombre' => 'Zootecnia',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ],
            [
                                    'codigo_pro' => '303',
                                    'nombre' => 'Zootecnia',
                                    'escuela_sigla' => 'ECAPMA',
                                    'fecha_registro' => '2025-07-14 17:47:39',
                                    'fecha_actualiza' => '2025-07-14 17:47:39',
                                ]
        ];

        foreach ($programas as $programa) {
            $escuelaId = Escuela::where('sigla', $programa['escuela_sigla'])->value('id');

            if (! $escuelaId) {
                continue;
            }

            Programa::updateOrCreate(
                ['codigo_pro' => $programa['codigo_pro']],
                [
                    'nombre' => $programa['nombre'],
                    'escuela_id' => $escuelaId,
                    'usuario_registra_id' => $adminId,
                    'usuario_actualiza_id' => null,
                    'fecha_registro' => $programa['fecha_registro'],
                    'fecha_actualiza' => $programa['fecha_actualiza'],
                    'estado_registro' => 'Activo',
                ]
            );
        }
    }
}
