@csrf
<div class="row g-3">
    <div class="col-12 col-md-6"><label class="form-label" for="nombre">Nombre</label><input id="nombre" name="nombre" value="{{ old('nombre', $decision->nombre) }}" maxlength="50" class="form-control @error('nombre') is-invalid @enderror" required>@error('nombre')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label class="form-label" for="proceso_disciplinario_id">Proceso</label><select id="proceso_disciplinario_id" name="proceso_disciplinario_id" class="form-select @error('proceso_disciplinario_id') is-invalid @enderror" required><option value="">Seleccione</option>@foreach ($procesos as $proceso)<option value="{{ $proceso->id }}" @selected((int) old('proceso_disciplinario_id', $decision->proceso_disciplinario_id) === $proceso->id)>#{{ $proceso->id }} - {{ $proceso->denuncia?->estudiante?->codigo_estu }} - {{ $proceso->denuncia?->estudiante?->nombre }} {{ $proceso->denuncia?->estudiante?->apellido }}</option>@endforeach</select>@error('proceso_disciplinario_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label class="form-label" for="tipo_decision">Tipo decision</label><select id="tipo_decision" name="tipo_decision" class="form-select @error('tipo_decision') is-invalid @enderror" required><option value="">Seleccione</option>@foreach ($tiposDecision as $tipo)<option value="{{ $tipo }}" @selected(old('tipo_decision', $decision->tipo_decision) === $tipo)>{{ $tipo }}</option>@endforeach</select>@error('tipo_decision')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label class="form-label" for="clasificacion_falta">Clasificacion falta</label><select id="clasificacion_falta" name="clasificacion_falta" class="form-select @error('clasificacion_falta') is-invalid @enderror"><option value="">Seleccione</option>@foreach ($clasificacionesFalta as $clasificacion)<option value="{{ $clasificacion }}" @selected(old('clasificacion_falta', $decision->clasificacion_falta) === $clasificacion)>{{ $clasificacion }}</option>@endforeach</select>@error('clasificacion_falta')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label class="form-label" for="fecha_sesion">Fecha sesion</label><input type="date" id="fecha_sesion" name="fecha_sesion" value="{{ old('fecha_sesion', $decision->fecha_sesion?->format('Y-m-d')) }}" class="form-control @error('fecha_sesion') is-invalid @enderror" required>@error('fecha_sesion')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label class="form-label" for="resultado">Resultado</label><textarea id="resultado" name="resultado" rows="5" class="form-control">{{ old('resultado', $decision->resultado) }}</textarea></div>
    <div class="col-12 col-md-6"><label class="form-label" for="observaciones">Observaciones</label><textarea id="observaciones" name="observaciones" rows="5" class="form-control">{{ old('observaciones', $decision->observaciones) }}</textarea></div>
    <div class="col-12"><label class="form-label" for="archivo">Archivo</label><input type="file" id="archivo" name="archivo" class="form-control @error('archivo') is-invalid @enderror" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png">@if ($decision->archivo)<div class="form-text">Archivo actual: <a href="{{ route('decisiones.archivo', $decision) }}">descargar</a></div>@endif @error('archivo')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary" type="submit">Guardar</button><a href="{{ route('decisiones.index') }}" class="btn btn-outline-secondary">Volver</a></div>
