@csrf
<div class="row g-3">
    <div class="col-12"><label class="form-label" for="decision_id">Decision</label><select id="decision_id" name="decision_id" class="form-select @error('decision_id') is-invalid @enderror" required><option value="">Seleccione</option>@foreach ($decisionesActivas as $decision)<option value="{{ $decision->id }}" @selected((int) old('decision_id', $sancion->decision_id) === $decision->id)>#{{ $decision->id }} - Proceso #{{ $decision->proceso_disciplinario_id }} - {{ $decision->procesoDisciplinario?->denuncia?->estudiante?->codigo_estu }} - {{ $decision->procesoDisciplinario?->denuncia?->estudiante?->nombre }} - {{ $decision->tipo_decision }}</option>@endforeach</select>@error('decision_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label class="form-label" for="tipo_sancion">Tipo sancion</label><select id="tipo_sancion" name="tipo_sancion" class="form-select @error('tipo_sancion') is-invalid @enderror" required><option value="">Seleccione</option>@foreach ($tiposSancion as $tipo)<option value="{{ $tipo }}" @selected(old('tipo_sancion', $sancion->tipo_sancion) === $tipo)>{{ $tipo }}</option>@endforeach</select>@error('tipo_sancion')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label class="form-label" for="estado_sancion">Estado sancion</label><select id="estado_sancion" name="estado_sancion" class="form-select @error('estado_sancion') is-invalid @enderror" required><option value="">Seleccione</option>@foreach ($estadosSancion as $estado)<option value="{{ $estado }}" @selected(old('estado_sancion', $sancion->estado_sancion) === $estado)>{{ $estado }}</option>@endforeach</select>@error('estado_sancion')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label class="form-label" for="numero_periodos">Numero periodos</label><input type="number" min="1" id="numero_periodos" name="numero_periodos" value="{{ old('numero_periodos', $sancion->numero_periodos ?? 1) }}" class="form-control @error('numero_periodos') is-invalid @enderror" required>@error('numero_periodos')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label class="form-label" for="periodo_inicial_sancion_id">Periodo inicial</label><select id="periodo_inicial_sancion_id" name="periodo_inicial_sancion_id" class="form-select @error('periodo_inicial_sancion_id') is-invalid @enderror"><option value="">Seleccione</option>@foreach ($periodos as $periodo)<option value="{{ $periodo->id }}" @selected((int) old('periodo_inicial_sancion_id', $sancion->periodo_inicial_sancion_id) === $periodo->id)>{{ $periodo->anio }} - {{ $periodo->periodo }}</option>@endforeach</select>@error('periodo_inicial_sancion_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label class="form-label" for="periodo_final_sancion_id">Periodo final</label><select id="periodo_final_sancion_id" name="periodo_final_sancion_id" class="form-select @error('periodo_final_sancion_id') is-invalid @enderror"><option value="">Seleccione</option>@foreach ($periodos as $periodo)<option value="{{ $periodo->id }}" @selected((int) old('periodo_final_sancion_id', $sancion->periodo_final_sancion_id) === $periodo->id)>{{ $periodo->anio }} - {{ $periodo->periodo }}</option>@endforeach</select>@error('periodo_final_sancion_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="descripcion">Descripcion</label><textarea id="descripcion" name="descripcion" rows="5" class="form-control @error('descripcion') is-invalid @enderror">{{ old('descripcion', $sancion->descripcion) }}</textarea>@error('descripcion')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary" type="submit">Guardar</button><a href="{{ route('sanciones.index') }}" class="btn btn-outline-secondary">Volver</a></div>
