@extends('layouts.app')
@section('title', 'Detalle apelacion | SME')
@section('content')
@php $estudiante = $apelacion->procesoDisciplinario?->denuncia?->estudiante; @endphp
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><h1 class="h3 mb-1">Detalle de apelacion</h1><div class="text-muted">Apelacion #{{ $apelacion->id }}</div></div><div class="d-flex gap-2"><a href="{{ route('pruebas.create', ['apelacion_id' => $apelacion->id]) }}" class="btn btn-outline-primary">Agregar prueba</a><a href="{{ route('apelaciones.edit', $apelacion) }}" class="btn btn-primary">Editar</a><a href="{{ route('apelaciones.index') }}" class="btn btn-outline-secondary">Volver</a></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><dl class="row mb-0">
<dt class="col-sm-3">ID</dt><dd class="col-sm-9">{{ $apelacion->id }}</dd><dt class="col-sm-3">Proceso</dt><dd class="col-sm-9">#{{ $apelacion->proceso_disciplinario_id }}</dd><dt class="col-sm-3">Estudiante</dt><dd class="col-sm-9">{{ $estudiante?->codigo_estu }} - {{ $estudiante?->nombre }} {{ $estudiante?->apellido }}</dd><dt class="col-sm-3">Tipo</dt><dd class="col-sm-9">{{ $apelacion->tipo_apelacion }}</dd><dt class="col-sm-3">Estado registro</dt><dd class="col-sm-9">{{ $apelacion->estado_registro }}</dd><dt class="col-sm-3">Motivo</dt><dd class="col-sm-9">{{ $apelacion->motivo ?? 'N/A' }}</dd><dt class="col-sm-3">Usuario registra</dt><dd class="col-sm-9">{{ $apelacion->usuarioRegistra?->nombre }} {{ $apelacion->usuarioRegistra?->apellido }}</dd><dt class="col-sm-3">Usuario actualiza</dt><dd class="col-sm-9">{{ $apelacion->usuarioActualiza?->nombre }} {{ $apelacion->usuarioActualiza?->apellido }}</dd>
</dl></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">Pruebas asociadas</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Nombre</th><th>Tipo</th><th>Procedencia</th><th>Estado</th><th>Archivo</th></tr></thead><tbody>@forelse ($apelacion->pruebas as $prueba)<tr><td>{{ $prueba->nombre }}</td><td>{{ $prueba->tipo_prueba }}</td><td>{{ $prueba->procedencia }}</td><td>{{ $prueba->estado_registro }}</td><td>@if ($prueba->archivo)<a href="{{ route('pruebas.archivo', $prueba) }}">Descargar</a>@else N/A @endif</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">No hay pruebas asociadas.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
